# Generated by Django 4.0.1 on 2022-03-02 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.CharField(max_length=255, verbose_name='Your note')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 3, 2, 16, 35, 45, 386990))),
                ('iduser', models.CharField(max_length=5, verbose_name='idUser')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
