# Generated by Django 4.0.1 on 2022-03-03 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 14, 24, 24, 473328)),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Your note'),
        ),
    ]
