# Generated by Django 4.0.1 on 2022-03-14 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_data_alter_note_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_notebook', models.CharField(max_length=100, verbose_name='Title')),
                ('iduser', models.CharField(max_length=5, verbose_name='idUser')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 18, 18, 5, 489514)),
        ),
    ]
