# Generated by Django 4.0.4 on 2022-04-26 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 13, 53, 39, 689477)),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='name_notebook',
            field=models.CharField(max_length=100, verbose_name='name_notebook'),
        ),
    ]
