# Generated by Django 4.0.4 on 2022-04-26 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_data_alter_notebook_name_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 13, 56, 42, 222399)),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='iduser',
            field=models.CharField(max_length=5, verbose_name='iduser'),
        ),
    ]
