# Generated by Django 4.0.4 on 2022-04-26 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_data_alter_notebook_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 14, 5, 51, 208538)),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
