# Generated by Django 4.0.4 on 2022-04-26 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_note_data_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 14, 6, 50, 650617)),
        ),
        migrations.AlterField(
            model_name='note',
            name='id_notebook',
            field=models.CharField(max_length=5, verbose_name='id_notebook'),
        ),
        migrations.AlterField(
            model_name='note',
            name='iduser',
            field=models.CharField(max_length=5, verbose_name='iduser'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='text'),
        ),
    ]
